#!/bin/sh /etc/rc.common
#    Copyright (C) 2017 Gui Iribarren <gui@altermundi.net>
#    Copyright (C) 2011 Fundacio Privada per a la Xarxa Oberta, Lliure i Neutral guifi.net
#
#    This is free software, licensed under the GNU General Public License v3.

START=91
USE_PROCD=1

NAME="bmx6"
BIN="/usr/sbin/$NAME"
CONF="/etc/config/$NAME"
DEBUG=0

start_service() {
    config_load "$NAME"

    cd /root/
    while pgrep -f mac80211.sh ; do sleep 1; done

    procd_open_instance "$NAME"
    procd_set_param command "$BIN" 
    procd_append_param command -f "$CONF" 
    procd_append_param command -d "$DEBUG"

    procd_set_param limits core="20000"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn

    config_foreach dev_trigger "dev"

    procd_close_instance
}

reload_service() {
    "$BIN" -c configReload
}

service_triggers() {
    procd_add_reload_trigger "bmx6"
}

dev_trigger() {
    local cfg="$1"
    config_get dev "$cfg" dev
    procd_add_interface_trigger "interface.*" ${dev} "/etc/init.d/$NAME" reload
}
